# This workflow runs tests for dev. branch 'windows-ci'. It does the following:
#   1. Checks if black formatting is followed.
#   2. Runs all tests.
#

name: test_push_action
on:
  push:
    branches:
      - main
      
env:
  SEISBENCH_CACHE_ROOT: seisbench_cache

jobs:
  black_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Black Style Check
        run: |
          pip install git+git://github.com/psf/black@20.8b1
          python -m black . --check

  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      # Load SeisBench cache to ensure data sets are always locally available
      - name: Cache SeisBench
        uses: actions/cache@v2
        with:
          path: ~/.seisbench
          key: seisbench-cache-v2
          restore-keys: |
            seisbench-cache-v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .
      
      - name: Test with pytest
        run: |
          pytest tests/
